### ISSUE TITLE
Suggestion: Add a license file

### ISSUE THREAD

**Issue by jbuberel** [SimonWaldherr/golang-examples#2]
For those of us who have to be sure of any source code we may download, it would be nice to add an official LICENSE file to the repository. I would suggest Apache 2.0:

http://www.apache.org/licenses/LICENSE-2.0

**Comment by SimonWaldherr** [comment]
thanks for the info, [it's MIT or cc-by-sa](https://github.com/SimonWaldherr/golang-examples#license) choose whatever fits best, i will add the file so it will be possible to auto-detect the license e.g. via GitHub API.
