### ISSUE TITLE
add more examples - #Hacktoberfest 2018

### ISSUE THREAD

**Issue by SimonWaldherr** [SimonWaldherr/golang-examples#31]
please feel free to add more examples

**Comment by tvytlx** [comment]
@SimonWaldherr 

request review https://github.com/SimonWaldherr/golang-examples/pull/33

**Comment by dimensi0n** [comment]
I could add an authentification example with JWT if you want

**Comment by SimonWaldherr** [comment]
@dimensi0n  yes, of course 👍

**Comment by Aashna-Agrawal** [comment]
@SimonWaldherr  Please review #49 Command Line Arguments Example.

**Comment by Arpit529Srivastava** [comment]
@SimonWaldherr  I could an about Go Mod examples and also about databases like MongoDB if you want

**Comment by SimonWaldherr** [comment]
@Arpit529Srivastava feel free to add a MongoDB example - please make it simple and easy to understand to match an example style.

**Comment by Arpit529Srivastava** [comment]
Sure, I will do it soon. Also, I have one question: will my contribution
count as a Hacktoberfest contribution?

thanks for responding

**Comment by SimonWaldherr** [comment]
Yes
