### ISSUE TITLE
non-std-lib readme does not show until you click on demo.md

### ISSUE THREAD

**Issue by crazcalm** [SimonWaldherr/golang-examples#34]
I found this to be awkward. I will send a PR renaming it to README.md

**Comment by SimonWaldherr** [comment]
the demo.md file is only an example file with *lorem ipsum* content for [/non-std-lib/markdown.go](https://github.com/SimonWaldherr/golang-examples/blob/master/non-std-lib/markdown.go).
It is not a "readme"-file, thanks anyway.
Feel free to write a new readme.md for the non-std-lib folder.
