### ISSUE TITLE
Create readme file for non-std-lib directory

### ISSUE THREAD

**Issue by crazcalm** [SimonWaldherr/golang-examples#36]
@SimonWaldherr Outside of the general statement that the examples in this directory all use at least one package outside of the std lib, what else do you want the readme to say?

**Comment by crazcalm** [comment]
@SimonWaldherr I think that covers all the points. Let me know if I missed anything.

**Comment by SimonWaldherr** [comment]
@crazcalm 👍 thanks, it looks great.
