### ISSUE TITLE
add more examples

### ISSUE THREAD

**Issue by SimonWaldherr** [SimonWaldherr/golang-examples#5]
please feel free to add more examples

**Comment by JoeBanks13** [comment]
@SimonWaldherr Added some more examples

**Comment by while-loop** [comment]
Could I refactor a certain example to make it more idiomatic for Go?

**Comment by JoeBanks13** [comment]
I guess so, just open a PR and owner will choose whichever one he wants.

**Comment by SimonWaldherr** [comment]
thanks guys 👍
